services:

  app:
    build: .
    container_name: "schoolManager"
    working_dir: /app

    volumes:
      - .:/app

    ports:
      - "5000:5000"

    depends_on:
      - mariadb
    
    environment:
      PYTHONUNBUFFERED: 1
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: school
      MYSQL_DATABASE: schoolDB
      MYSQL_PASSWORD: admin

    networks:
      - backend

  mariadb:
    image: mariadb:latest
    container_name: "mariadb"

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: school
      MYSQL_DATABASE: schoolDB
      MYSQL_PASSWORD: admin

#     volumes:
#       - schoolDB:/var/lib/mysql

    ports:
      - "5467:5467"
    
    networks:
      - backend

networks:
  backend:
    driver: bridge
