version: "3"

services:

  postgres:
    image: postgres:latest
    container_name: "happyRotel_postgres"

    environment:
      POSTGRES_USER: "happyRotel"
      POSTGRES_PASSWORD: "shinyhappypeople"
      POSTGRES_DB: "happyRotel"

    restart: always

    volumes:
      - postgres_data:/var/lib/postgres/data

    ports:
      - "2601:5432"
    

  #
  app:
    build: 
      context: .
      dockerfile: dockerfile

    command: python3 -u run.py
    # command: ls -a

    volumes:
      - ./app:/happyRotel

    container_name: "happyRotel_flask"

    environment:
      HAPPYROTEL_DB_USER: "happyRotel"
      HAPPYROTEL_DB_PASSWORD: "shinyhappypeople"
      HAPPYROTEL_DB_DATABASE: "happyRotel"
      HAPPYROTEL_DB_HOST: "postgres"

    ports:
      - "5000:5000"

    depends_on:
      - postgres

volumes:
  postgres_data: {}
