FROM python:3.13.1
LABEL maintainer="CastCris author"

RUN useradd -ms /bin/sh -u 1001 app
USER app

#
ENV workdir "/happyRotel"
ENV appdir "./app"
WORKDIR ${workdir}

COPY ${appdir}/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY --chown=app:app  ${appdir} .
